[project]
authors = ["Tristan F. <pub.tristanf@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
name = "setup-pixi-cache-false"
version = "0.1.0"

[tasks]

[dependencies]
go = ">=1.24.4,<2"
pandas = ">=2.3.0,<3"
