[project]
authors = ["Tristan F. <pub.tristanf@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
name = "setup-pixi-cache-false"
version = "0.1.0"

[tasks]

[dependencies]
"adjusttext" = "0.7.3"
"snakemake" = "9.6.0"
"docker" = "6.1.0"
"matplotlib" = "3.10.3"
"networkx" = "2.8"
"pandas" = "2.3.0"
"numpy" = "2.3.0"
"pip" = "25.1.1"
"requests" = "2.28"
"scikit-learn" = "1.7.0"
"seaborn" = "0.13.2"
"spython" = "0.2"
"commonmark" = "0.9"
"docutils" = "0.19"
"jinja2" = "3.1"
"mock" = "4.0"
"recommonmark" = "0.7"
"sphinx" = "6.0"
"graphspace_python" = "1.3.1"
