[project]
authors = ["Tristan F. <LeoDog896@hotmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "setup-pixi-cache-false"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
go = ">=1.24.4,<2"
