name: Test

on: [push]

jobs:
  test:
    name: Run test cases and workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
  test2:
    name: Run test cases and workflow with cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pixi - cache false
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          cache: false

  test3:
    name: Run test cases and workflow with locked
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pixi - cache false
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          locked: false
  
  test4:
    name: Run test cases and workflow with cache locked
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pixi - cache false
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          cache: false
          locked: false
